### ISSUE TITLE
Gracefull shutdown is not working properly if you kill the program to early

### ISSUE THREAD

**Issue by iotafr** [etf1/kafka-mongo-watcher#2]
If you kill the program before the worker group was created, the graceful shutdown is not working
```
<info> Tech HTTP server started {"facility":"kafka-mongo-watcher","version":"wip","addr":":8001","file":"/usr/local/go/src/runtime/asm_amd64.s","line":1357}
<info> Connected to kafka producer {"line":31,"facility":"kafka-mongo-watcher","version":"wip","bootstrao-servers":"127.0.0.1:9092","file":"/Volumes/iotaDisk/Users/iota/Documents/workspace/go/src/github.com/etf1/kafka-mongo-watcher/internal/service/kafka.go"}
<info> Connected to mongodb database {"facility":"kafka-mongo-watcher","version":"wip","line":29,"uri":"mongodb://root:toor@127.0.0.1:27011,127.0.0.1:27012,127.0.0.1:27013/local?replicaSet=replicaset","file":"/Volumes/iotaDisk/Users/iota/Documents/workspace/go/src/github.com/etf1/kafka-mongo-watcher/internal/service/mongo.go"}
^CPress `ctrl+c` again to kill application.
Shutting down.
<info> Signal received: gracefully stopping application {"signal":"interrupt","file":"/usr/local/go/src/runtime/asm_amd64.s","line":1357,"facility":"kafka-mongo-watcher","version":"wip"}
panic: sync: negative WaitGroup counter

goroutine 73 [running]:
sync.(*WaitGroup).Add(0xc0001a6d08, 0xffffffffffffffff)
        /usr/local/go/src/sync/waitgroup.go:74 +0x139
sync.(*WaitGroup).Done(...)
        /usr/local/go/src/sync/waitgroup.go:99
github.com/etf1/kafka-mongo-watcher/internal/worker.(*worker).Close(0xc0001a6cb0)
        /Volumes/iotaDisk/Users/iota/Documents/workspace/go/src/github.com/etf1/kafka-mongo-watcher/internal/worker/worker.go:47 +0x3c
main.handleExitSignal.func1(0x4935cc0, 0xc0000241a8)
        /Volumes/iotaDisk/Users/iota/Documents/workspace/go/src/github.com/etf1/kafka-mongo-watcher/cmd/watcher/main.go:42 +0x1cf
created by github.com/gol4ng/signal.Subscribe.func1
        /Volumes/iotaDisk/Users/iota/Documents/workspace/go/pkg/mod/github.com/gol4ng/signal@v1.1.0/subscriber.go:39 +0x5e
exit status 2
```

It happens if I kill the watcher before the worker group was created
https://github.com/etf1/kafka-mongo-watcher/blob/6d907ebc3ea7b3f7c737f62b01e54a0653292d12/internal/worker/worker.go#L46

In that case, the waitGroup is empty or not full and the Done() method is called too many times.

**Comment by eko** [comment]
Thanks, this is now fixed by maintaining a number of running workers (https://github.com/etf1/kafka-mongo-watcher/commit/2a462c83cf86843e441d85ff020621afe40d9df2)

**Comment by iotafr** [comment]
👍
